### ISSUE TITLE
Functionality

### ISSUE THREAD

**Issue by Clanwarz-zz** [Alexr03/TCAdminCronsModule#2]
Alex,

The functionality routine remains unclear. What is this plugin looking for? Is it scanning the client files?

```
Minecraft Vanilla Update Cron] Game Update already exists for 1.16-pre6
[Minecraft Vanilla Update Cron] Game Update already exists for 1.16-pre5
[Minecraft Vanilla Update Cron] Game Update already exists for 1.16-pre4
[Minecraft Vanilla Update Cron] Game Update already exists for 1.16.2
```

Where are these files being deposited? How do clients access them?

Thanks!

**Comment by Alexr03** [comment]
Hi,
This module automatically adds Game Updates to the Minecraft Game and allows the user to install them. Check out the Game Updates page on the minecraft game.

**Comment by Clanwarz-zz** [comment]
Alex,

Where were you 7 years ago!

This is really nice. I've yet to explore in detail but my hats off to you.

Job well done!

Thank you for your hard work.

**Comment by Alexr03** [comment]
7 years ago..
Probably just starting secondary school (In the UK at least) haha. 

Let me know if you got more questions :)

Cheers
