### ISSUE TITLE
uMod integration + Twitch/Curse mod packs

### ISSUE THREAD

**Issue by AdamG100** [Alexr03/TCAdminCronsModule#3]
Please can you look into the following:
Add rust plugins via umod into the mod manager
Add Twitch/Curse mod packs into the mod manager

Thanks :)

**Comment by Alexr03** [comment]
I don't think that umod has a API to get the list of mods.
Link me Twitch/Curse mod packs please

**Comment by AdamG100** [comment]
Created separate module for this:  https://github.com/Alexr03/TCAdminCustomMods/
