### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by AngliNex** [Alexr03/TCAdminCronsModule#5]
--
Line 1:  @using System.Web.Mvc.Html Line 2:  @using Alexr03.Common.Misc.Strings Line 3:  @using Alexr03.Common.Web.Extensions Line 4:  @using Kendo.Mvc.UI

**Comment by AngliNex** [comment]
Description: An error occurred during the compilation of a resource required to service this request. Please review the following specific error details and modify your source code appropriately.

Compiler Error Message: CS0246: The type or namespace name 'Alexr03' could not be found (are you missing a using directive or an assembly reference?)

Source Error:
 
--
Line 1:  @using System.Web.Mvc.Html Line 
2:  @using Alexr03.Common.Misc.Strings Line 
3:  @using Alexr03.Common.Web.Extensions Line 
4:  @using Kendo.Mvc.UI

Source File: c:\Program Files\TCAdmin2\ControlPanel.MVC\Views\Default\TCAdminCrons.Controllers\Crons\Configuration.cshtml    Line: 2

**Comment by Alexr03** [comment]
Install Alexr03.Common

**Comment by AngliNex** [comment]
I figured it out like a n hour after I sent this.  I feel silly.

Is there some kind of guide on how to use Crons now that I have it working?  I'm not entirely sure what I'm looking at.
My game dev left me high and dry and I'm just trying to survive long enough to find a new one.

**Comment by Alexr03** [comment]
When you run the cron it will add paper, bukkit etc as mods on the game where you set the game ID. You can then install them mods

**Comment by AngliNex** [comment]
What about picking the Minecraft version?

**Comment by Alexr03** [comment]
It also grabs the latest minecraft versions & snapshots
